# Generated by Django 5.1.7 on 2025-03-14 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Khatmah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('khatmah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='api.khatmah')),
            ],
        ),
        migrations.CreateModel(
            name='JuzAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('juz_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('khatmah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.khatmah')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.participant')),
            ],
            options={
                'unique_together': {('juz_number', 'khatmah')},
            },
        ),
    ]
