# Generated by Django 4.2.20 on 2025-03-15 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_khatmah_end_date_khatmah_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HijriMonth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_ar', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('gregorian_start', models.DateField()),
                ('gregorian_end', models.DateField()),
                ('moon_sighting_data', models.JSONField(blank=True, null=True)),
                ('calendar_data', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['year', 'number'],
                'unique_together': {('number', 'year')},
            },
        ),
        migrations.CreateModel(
            name='HijriEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('day', models.IntegerField()),
                ('year_of_event', models.IntegerField(blank=True, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('event_type', models.CharField(blank=True, max_length=50, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.hijrimonth')),
            ],
            options={
                'ordering': ['month__number', 'day'],
            },
        ),
        migrations.CreateModel(
            name='AstronomicalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_ar', models.CharField(max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='astronomical_events', to='api.hijrimonth')),
            ],
        ),
    ]
