# Generated by Django 4.2.20 on 2025-03-25 08:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_hijrimonth_hijrievent_astronomicalevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatmah',
            name='khatmah_type',
            field=models.CharField(choices=[('juz', 'Juz Based'), ('surah', 'Surah Based')], default='juz', max_length=10),
        ),
        migrations.CreateModel(
            name='SurahAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surah_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('khatmah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surah_assignments', to='api.khatmah')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surah_assignments', to='api.participant')),
            ],
            options={
                'unique_together': {('surah_number', 'khatmah')},
            },
        ),
    ]
