# Generated by Django 4.2.20 on 2025-03-25 09:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_khatmah_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatmah',
            name='creator_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
