# Generated by Django 4.2.20 on 2025-03-26 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_khatmah_creator_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='khatmah',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='khatmah_images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif'])]),
        ),
    ]
